<a href="https://colab.research.google.com/github/priyadharshini2207/lab_record/blob/main/Finance(logistic).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/machine_learning/SVM(finance_train).csv")
df.head()

Loan_ID Gender Married  ... Credit_History Property_Area Loan_Status
0  LP001002   Male      No  ...            1.0         Urban           Y
1  LP001003   Male     Yes  ...            1.0         Rural           N
2  LP001005   Male     Yes  ...            1.0         Urban           Y
3  LP001006   Male     Yes  ...            1.0         Urban           Y
4  LP001008   Male      No  ...            1.0         Urban           Y

[5 rows x 13 columns]

In [ ]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [ ]:
df['Gender'].value_counts()

Male      489
Female    112
Name: Gender, dtype: int64

In [ ]:
df.Gender = df.Gender.fillna('Male')

In [ ]:
df['Married'].value_counts()

Yes    398
No     213
Name: Married, dtype: int64

In [ ]:
df.Married = df.Married.fillna('Yes')

In [ ]:
df['Dependents'].value_counts()

0     345
1     102
2     101
3+     51
Name: Dependents, dtype: int64

In [ ]:
df.Dependents = df.Dependents.fillna('0')

In [ ]:
df.Self_Employed = df.Self_Employed.fillna('No')

In [ ]:
df.LoanAmount = df.LoanAmount.fillna(df.LoanAmount.mean())

In [ ]:
df.Loan_Amount_Term = df.Loan_Amount_Term.fillna(360.0)

In [ ]:
df.Credit_History = df.Credit_History.fillna(1.0)

In [ ]:
df.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le=LabelEncoder()

In [ ]:
df.Loan_ID=le.fit_transform(df.Loan_ID)
df.Gender=le.fit_transform(df.Gender)
df.Married=le.fit_transform(df.Married)
df.Dependents	=le.fit_transform(df.Dependents)
df.Education	=le.fit_transform(df.Education)
df.Self_Employed=le.fit_transform(df.Self_Employed)
df.ApplicantIncome=le.fit_transform(df.ApplicantIncome)
df.CoapplicantIncome=le.fit_transform(df.CoapplicantIncome)
df.LoanAmount	=le.fit_transform(df.LoanAmount	)
df.Loan_Amount_Term		=le.fit_transform(df.Loan_Amount_Term)
df.Credit_History=le.fit_transform(df.Credit_History)
df.Property_Area=le.fit_transform(df.Property_Area)
df.Loan_Status=le.fit_transform(df.Loan_Status)

In [ ]:
df.head()

Loan_ID  Gender  Married  ...  Credit_History  Property_Area  Loan_Status
0        0       1        0  ...               1              2            1
1        1       1        1  ...               1              0            0
2        2       1        1  ...               1              2            1
3        3       1        1  ...               1              2            1
4        4       1        0  ...               1              2            1

[5 rows x 13 columns]

In [ ]:
x = df.iloc[:, 1: 12].values
y = df.iloc[:, 12].values

In [ ]:
x

array([[1, 0, 0, ..., 8, 1, 2],
       [1, 1, 1, ..., 8, 1, 0],
       [1, 1, 0, ..., 8, 1, 2],
       ...,
       [1, 1, 1, ..., 8, 1, 2],
       [1, 1, 2, ..., 8, 1, 2],
       [0, 0, 0, ..., 8, 0, 1]])

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split( x, y, test_size=0.33, random_state=0)

In [ ]:
x_train

array([[1, 1, 2, ..., 5, 0, 2],
       [1, 1, 0, ..., 8, 1, 0],
       [1, 1, 3, ..., 8, 1, 0],
       ...,
       [1, 1, 3, ..., 8, 1, 1],
       [1, 1, 0, ..., 8, 1, 2],
       [0, 1, 0, ..., 8, 1, 1]])

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
y_pred = classifier.predict(x_test)

In [ ]:
y_pred

array([1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1])

In [ ]:
from sklearn import metrics
print('The accuracy of Logistic Regression is: ', metrics.accuracy_score(y_pred, y_test))

The accuracy of Logistic Regression is:  0.8226600985221675
